# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E02_PromedioNumeros.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 748)
        MainWindow.setStyleSheet("background-color: rgb(255, 199, 246);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 12pt \"Yu Gothic UI\";")
        self.label.setObjectName("label")
        self.btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar.setGeometry(QtCore.QRect(470, 110, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_agregar.setFont(font)
        self.btn_agregar.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-radius:25px;\n"
"color: rgb(0,0,0);\n"
"border: 5px solid white;\n"
"font: 75 20pt \"Yu Gothic UI\";")
        self.btn_agregar.setObjectName("btn_agregar")
        self.txt_calificacion = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_calificacion.setGeometry(QtCore.QRect(180, 30, 271, 71))
        self.txt_calificacion.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(116, 183, 255);\n"
"border: 5px solid white;")
        self.txt_calificacion.setObjectName("txt_calificacion")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 200, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 12pt \"Yu Gothic UI\";")
        self.label_3.setObjectName("label_3")
        self.txt_promedio = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_promedio.setGeometry(QtCore.QRect(180, 190, 271, 71))
        self.txt_promedio.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(116, 183, 255);\n"
"border: 5px solid white;")
        self.txt_promedio.setObjectName("txt_promedio")
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(220, 310, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_guardar.setFont(font)
        self.btn_guardar.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-radius:25px;\n"
"color: rgb(0,0,0);\n"
"border: 5px solid white;\n"
"font: 75 20pt \"Yu Gothic UI\";")
        self.btn_guardar.setObjectName("btn_guardar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Calificacion"))
        self.btn_agregar.setText(_translate("MainWindow", "Agregar"))
        self.label_3.setText(_translate("MainWindow", "Promedio"))
        self.btn_guardar.setText(_translate("MainWindow", "Guardar"))
