# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E04_EjemploLineEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(218, 255, 212);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_nombre.setGeometry(QtCore.QRect(270, 160, 271, 101))
        self.txt_nombre.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 170, 255);")
        self.txt_nombre.setObjectName("txt_nombre")
        self.btn_saludar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_saludar.setGeometry(QtCore.QRect(270, 280, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.btn_saludar.setFont(font)
        self.btn_saludar.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"border-radius:25px;\n"
"color: rgb(170, 255, 255);\n"
"border: 5px solid blue;")
        self.btn_saludar.setObjectName("btn_saludar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 70, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_saludar.setText(_translate("MainWindow", "SALUDAR"))
        self.label.setText(_translate("MainWindow", "Nombre:"))
