# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E10_checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 625)
        MainWindow.setStyleSheet("background-color: rgb(131, 208, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 420, 201, 191))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logos/equipo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 10, 151, 151))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/logos/FIT_logo_vertical.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 221, 131))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/logos/log_uat_nuevo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 190, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 240, 221, 171))
        self.groupBox.setObjectName("groupBox")
        self.cb_jugar = QtWidgets.QCheckBox(self.groupBox)
        self.cb_jugar.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.cb_jugar.setObjectName("cb_jugar")
        self.cb_dormir = QtWidgets.QCheckBox(self.groupBox)
        self.cb_dormir.setGeometry(QtCore.QRect(20, 70, 81, 20))
        self.cb_dormir.setObjectName("cb_dormir")
        self.cb_salir = QtWidgets.QCheckBox(self.groupBox)
        self.cb_salir.setGeometry(QtCore.QRect(20, 110, 81, 20))
        self.cb_salir.setObjectName("cb_salir")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 240, 231, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cb_cine = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_cine.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.cb_cine.setObjectName("cb_cine")
        self.cb_playa = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_playa.setGeometry(QtCore.QRect(20, 80, 81, 20))
        self.cb_playa.setObjectName("cb_playa")
        self.cb_plaza = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_plaza.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.cb_plaza.setObjectName("cb_plaza")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Pasatiempo:"))
        self.label_5.setText(_translate("MainWindow", "Lugares Favoritos:"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.cb_jugar.setText(_translate("MainWindow", "Jugar"))
        self.cb_dormir.setText(_translate("MainWindow", "Dormir"))
        self.cb_salir.setText(_translate("MainWindow", "salir"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.cb_cine.setText(_translate("MainWindow", "Cine"))
        self.cb_playa.setText(_translate("MainWindow", "Playa"))
        self.cb_plaza.setText(_translate("MainWindow", "Plaza"))
import resource_rc
