# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P2_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit
from mpl_toolkits.axisartist.angle_helper import select_step_degree


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 675)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 450, 201, 191))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logos/equipo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, -10, 161, 181))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/logos/FIT_logo_vertical.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 221, 131))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/logos/log_uat_nuevo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 190, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(290, 170, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txt_num1.setFont(font)
        self.txt_num1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.txt_num1.setObjectName("txt_num1")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 300, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(290, 280, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txt_num2.setFont(font)
        self.txt_num2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.txt_num2.setObjectName("txt_num2")
        self.btn_suma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_suma.setGeometry(QtCore.QRect(290, 530, 151, 51))
        self.btn_suma.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_suma.setObjectName("btn_suma")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 410, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.txt_num3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num3.setGeometry(QtCore.QRect(290, 400, 311, 61))
        self.txt_num3.setFont(font)
        self.txt_num3.setText("")
        self.txt_num3.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_num3.setObjectName("txt_num3")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Numero 1:"))
        self.label_5.setText(_translate("MainWindow", "Numero 2:"))
        self.btn_suma.setText(_translate("MainWindow", "Suma"))
        self.label_6.setText(_translate("MainWindow", "Numero 3:"))

import resource_rc
