# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P3_Calcular_IMC.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 675)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(130, 130, 195);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 450, 201, 191))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logos/equipo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, -10, 161, 181))
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/logos/FIT_logo_vertical.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 221, 131))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/logos/log_uat_nuevo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 75 18pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.txt_altura = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_altura.setGeometry(QtCore.QRect(310, 180, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txt_altura.setFont(font)
        self.txt_altura.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.txt_altura.setObjectName("txt_altura")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 300, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 75 18pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.txt_peso = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_peso.setGeometry(QtCore.QRect(310, 290, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txt_peso.setFont(font)
        self.txt_peso.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.txt_peso.setObjectName("txt_peso")
        self.btn_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcular.setGeometry(QtCore.QRect(350, 420, 231, 61))
        self.btn_calcular.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 18pt \"Times New Roman\";")
        self.btn_calcular.setObjectName("btn_calcular")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Altura (m)"))
        self.label_5.setText(_translate("MainWindow", "Peso (Kg)"))
        self.btn_calcular.setText(_translate("MainWindow", "CALCULAR IMC"))
import resource_rc
